# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: fullstack
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80            # Service port
      targetPort: 80      # Container port
      nodePort: 30080     # Fixed NodePort (optional, else K8s will assign random between 30000-32767)
  type: NodePort
